### PR TITLE
Added support for FAQ Page JSON-LD

### PR DESCRIPTION
**Pull request by Myoxocephalus**
Include support for [FAQ Page](https://developers.google.com/search/docs/data-types/faqpage) and corresponding tests and documentation.

### CODE REVIEW

**Comment by Myoxocephalus** [comment]
Hi!
Now it fixed :).
Once merged i can send as ts PR to the master branch.

**Comment by garmeeh** [comment]
Hey @Myoxocephalus, looks like something might of get messed up 🤔 Lot's of conflicts and file changes.

**Comment by Myoxocephalus** [comment]
Hi @garmeeh , sorry for the late response, now it should be fixed.

**Comment by Myoxocephalus** [comment]
@garmeeh i updated the code to be typescript and changed the base branch to master.

**Comment by Gr8z** [comment]
@Myoxocephalus this is great, would you also be able to take a look at Logo and Software data?

Thank you

**Comment by Myoxocephalus** [comment]
> @Myoxocephalus this is great, would you also be able to take a look at Logo and Software data?
> 
> Thank you

Sure, can take a look at that next week.

**Comment by garmeeh** [comment]
@all-contributors please add @Myoxocephalus for doc code test

**Comment by garmeeh** [comment]
Thanks @Myoxocephalus

**Pull request merged**
