### PR TITLE
Optionally prevent rendering of default robots meta tags

### PR DESCRIPTION
**Pull request by jaredrolt**
SEO specialists sometimes prefer not to have default `robots` and `googlebot` meta tags rendered on the page.

This PR adds a config option `doNotRenderDefaultRobotsTags` to prevent rendering these tags by default.

- [x] Have you updated the documentation to go with your changes?
- [x] Have you written or updated unit tests?
- [x] Have you written an integration test in the test app supplied?

### CODE REVIEW

**Comment by jaredrolt** [comment]
Hey @garmeeh, thanks for the handy plugin. Did you have any thoughts on this additional config option?

**Comment by garmeeh** [comment]
Hey @jaredrolt thanks for the pull request and sorry for the delay.

I think this very similar to #458 😅 

I think the solution I suggested on #458 might cover this use case also.

Would love to hear your thoughts on it?

Maybe there is a use case to keep the options separate 🤔

**Comment by jaredrolt** [comment]
> Hey @jaredrolt thanks for the pull request and sorry for the delay.
> 
> I think this very similar to #458 😅
> 
> I think the solution I suggested on #458 might cover this use case also.
> 
> Would love to hear your thoughts on it?
> 
> Maybe there is a use case to keep the options separate 🤔

It does look very similar - perhaps both `googlebot` and `robots` could be optionally disabled with the same flag.

**Comment by garmeeh** [comment]
I will be adding this feature shortly.

**Pull request closed without merging**
