### PR TITLE
Add carousel jsonld

### PR DESCRIPTION
**Pull request by statebait**
## Description of Change(s):

Implements #415 

Adds the carousel jsonld component. Refer here- https://developers.google.com/search/docs/data-types/carousel

The following types are currently supported: 
- Default (the summary list)
- Course
- Movie
- Recipe

Have updated all the e2e cypress tests and the docs in the README

### CODE REVIEW

**Comment by statebait** [comment]
@garmeeh

**Comment by garmeeh** [comment]
@all-contributors please add @statebait for code, doc, test

**Review by garmeeh — APPROVED** [review]
🎉 Thank you for adding this feature. 

Only comment I would have is that if the `jsonld`  is updated in `recipe.tsx` it would also have to be updated in `carousel.tsx`. This s only minor and can be updated in a future refactor.

**Comment by statebait** [comment]
> 🎉 Thank you for adding this feature.
> 
> Only comment I would have is that if the `jsonld` is updated in `recipe.tsx` it would also have to be updated in `carousel.tsx`. This s only minor and can be updated in a future refactor.

Thanks!! Will make a PR to use a single function to generate the jsonld for recipe (and course).

**Pull request merged**
