### PR TITLE
[Feature] add reviews to local bussines json ld

### PR DESCRIPTION
**Pull request by adrianu197**
## Description of Change(s):

As we can see the review list is a [recommended prop by google](https://developers.google.com/search/docs/data-types/local-business) so this PR will add it as an optional prop in LocalBusiness JSON-LD. I added the exact properties used in schem.org examples for [Review](https://schema.org/Review) and for [Rating](https://schema.org/Rating), i'm open to add another properties if needed.

---

Some things to help get a PR reviewed and merged faster:

- Have you updated the documentation to go with your changes?  ✅
- Have you written or updated unit tests? ✅
- Have you written an integration test in the test app supplied? ✅

The above are generally required on all PR's.

Please have a read of the Contributing Guide for full details.

https://github.com/garmeeh/next-seo/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by garmeeh — APPROVED** [review]
Thanks for the contribution 😄

**Comment by garmeeh** [comment]
@adrianu197 could you address the conflict and I will get this merged.

**Comment by adrianu197** [comment]
> @adrianu197 could you address the conflict and I will get this merged.

I want to add some more optional props(https://schema.org/potentialAction , https://schema.org/areaServed and https://schema.org/makesOffer) in this PR if it's ok:
If you want me to add them in other PR then i can solve the conflicts and finish this.

**Comment by garmeeh** [comment]
Hey @adrianu197 adding to this PR would be perfect thanks.

**Comment by garmeeh** [comment]
@all-contributors please add @adrianu197 code doc test

**Pull request merged**
