### PR TITLE
Add optional type to LinkTag

### LINKED ISSUE #910: additionalLinkTags does not support "as" and "crossorigin" attributes
When adding link tags that are not handled by default, attempt to include the `as` and `crossorigin` attributes result into a TypeScript error TS2769.

<details><summary>TypeScript Error</summary>

```sh
> tsc

pages/_app.tsx:21:7 - error TS2769: No overload matches this call.
  Overload 2 of 2, '(props: NextSeoProps, context: any): NextSeo', gave the following error.
    Type '{ rel: string; href: string; crossOrigin: string; }' is not assignable to type 'LinkTag'.
      Object literal may only specify known properties, and 'crossOrigin' does not exist in type 'LinkTag'.
  Overload 2 of 2, '(props: NextSeoProps, context: any): NextSeo', gave the following error.
    Type '{ rel: string; href: string; as: string; type: string; crossOrigin: string; }' is not assignable to type 'LinkTag'.
      Object literal may only specify known properties, and 'as' does not exist in type 'LinkTag'.

 21       <NextSeo
          ~~~~~~~~
 22         additionalLinkTags={[
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 45         ]}
    ~~~~~~~~~~
 46       />
    ~~~~~~~~



Found 1 error.
```

</details>

It will be great to add them as optional attributes to the link tag so as to enable preloading of resources for performance optimisation.

The following is the attempted [`additionalLinkTags`](https://github.com/garmeeh/next-seo#additional-link-tags) configuration.

```tsx
// _app.tsx
import type { AppProps } from 'next/app'
import { DefaultSeo, NextSeo } from 'next-seo'
import SEO from '../next-seo.config'
import '../styles/globals.css'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <DefaultSeo {...SEO} />
      <NextSeo
        additionalLinkTags={[
          {
            rel: 'preload',
            href: '/font/nunito-v20-latin-regular.woof2',
            as: 'font',
            type: 'font/woff2',
            crossOrigin: 'anonymous'
          }
        ]}
      />
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
```

### PR DESCRIPTION
**Pull request by nyedidikeke**
Include "as" and "crossOrigin" as optional type of the LinkTag interface so as to resolve #910.

### CODE REVIEW

**Comment by nyedidikeke** [comment]
@garmeeh Is there anything you would like me to check before assessing for merger?

**Comment by garmeeh** [comment]
Thank you for the contribution  @nyedidikeke 🙏 😄 

Can you please add one more test to `seo.spec.js` and I will be happy to merge.

**Review by garmeeh — CHANGES_REQUESTED** [review]
Thank you for the contribution @nyedidikeke 🙏 😄

Can you please add one more test to seo.spec.js and I will be happy to merge.

**Comment by nyedidikeke** [comment]
@garmeeh Done.

**Review by garmeeh — APPROVED** [review]
Amazing! Thank you 💪

**Pull request merged**
