### PR TITLE
Remove special/hidden characters from jsonLd

### PR DESCRIPTION
**Pull request by Qrymy**
## Description of Change(s):
At v4.10.0, I've faced a critical issue using `<~JsonLd>` components.
```
unexpected token /empty/ in JSON
```

To fix, I added a function to remove special/hidden characters to `minifyJsonLd`.

### CODE REVIEW

**Comment by zeekrey** [comment]
Got the same error. Please merge and release ❤

**Comment by Qrymy** [comment]
@zeekrey 
You can avoid this error temporarily, follow this example.

```
const removeSpecialCharacters = (data: string) => {
  return data.replace(/[\u0000-\u0019]/g, '')
}

<ProductJsonLd 
  productName={removeSpecialCharacters(name)}
  description={removeSpecialCharacters(description)}
  ...
/>
```

Try it!

**Comment by garmeeh** [comment]
@all-contributors add @Qrymy  for code

**Review by garmeeh — APPROVED** [review]
Thanks for the fix.

**Pull request merged**
