### PR TITLE
fix(925): match documentation with contactPoint for organisation

### PR DESCRIPTION
**Pull request by stijnbernards**
## Description of Change(s):

---

To help get PR's merged faster, the following is required:

[*] Updated the documentation
[*] Unit/Cypress test covering all cases

---

Also changed the function in CorporateContact to match the Organisation.
Kept the incorrect contactPoints prop intact but as deprecated to make sure we make no breaking change.

### CODE REVIEW

**Review by garmeeh — CHANGES_REQUESTED** [review]
Hey @stijnbernards thank you for the PR. 🙏 

Wold you be able to add a Cypress test to cover the new `contactPoint` prop. 

We can keep the old Cypress for `contactPoints` as we will need this until it is removed in a future major release.

**Comment by stijnbernards** [comment]
@garmeeh Sure, I'll work on this tomorrow 😄

**Comment by stijnbernards** [comment]
Sorry @garmeeh Didn't get the time to work on this yet, will hope to get to it soon!

**Comment by garmeeh** [comment]
Hey @stijnbernards thanks for the PR. Going to close this for now. I think these changes were snuck in just before end of hacktober just before it ended. Please open up a new PR if there anything was missed.

**Pull request closed without merging**
