### PR TITLE
Add missing og images attributes

### PR DESCRIPTION
**Pull request by simrobin**
## Description of Change(s):

Fixes: https://github.com/garmeeh/next-seo/issues/712

This changes add missing OpenGraph tags to the [image structured property](https://ogp.me/#structured).
The attributes `type` and `secure_url` where missing for image and I added them in 6d061a6.
The second commit (e971e71) is a proposition of a refactoring for logic centralization of images and videos (which is the same: the 2 structed properties have the same fields). I can easily remove or update it if it's not what you're aiming for in this library.

💡 BTW: I struggled a bit to launch E2E locally, I had to run `yarn run e2e:build` before `yarn test:e2e` to make it work, is it normal ? I also noticed that running E2E updates my `./e2e/.next-env.d.ts` (even without my updates), but I don't know why.

---

Some things to help get a PR reviewed and merged faster:

- Have you updated the documentation to go with your changes? **Yes** (first commit: 6d061a6)
- Have you written or updated unit tests? **Yes** (first commit: 6d061a6)
- Have you written an integration test in the test app supplied? **Yes** (first commit: 6d061a6)

The above are generally required on all PR's.

Please have a read of the Contributing Guide for full details.

https://github.com/garmeeh/next-seo/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by garmeeh** [comment]
@all-contributors please add @simrobin doc code test

**Review by garmeeh — APPROVED** [review]
Thanks for refactoring and updates 😄

**Comment by simrobin** [comment]
@garmeeh thanks for the review and merge 🙂

**Comment by garmeeh** [comment]
No problem @simrobin thanks for the contribution. And the coffee 😉

**Pull request merged**
