### PR TITLE
Multiple alternate languages

### PR DESCRIPTION
**Pull request by petertulala**
Closes https://github.com/garmeeh/next-seo/issues/114

### CODE REVIEW

**Comment by garmeeh** [comment]
Hey @petertulala, thanks for the PR. The tests are currently failing on this if you could take a look. 

😞 Travis stopped showing up here so will need to take a look at why.

**Comment by petertulala** [comment]
@garmeeh Sorry for the delay. I've fixed the failing tests. Please have a look.

**Comment by garmeeh** [comment]
@all-contributors please add @petertulala for code, test

**Comment by garmeeh** [comment]
Thanks @petertulala for the PR 💪

**Comment by garmeeh** [comment]
@petertulala because this is a breaking change I am going to group it with #117

**Pull request merged**
