### PR TITLE
feat: support article author url

### PR DESCRIPTION
**Pull request by xiaotiandada**
## Description of Change(s):

minimal modification

before
image

after
image

---

To help get PR's merged faster, the following is required:

- [x] Updated the documentation
- [x] Unit/Cypress test covering all cases

Please link to relevant Google Docs or schema.org docs for what you are adding so we can review.

Please have a read of the Contributing Guide for full details.

https://github.com/garmeeh/next-seo/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by xiaotiandada** [comment]
@garmeeh  review code, please

**Comment by xiaotiandada** [comment]
https://developers.google.com/search/docs/advanced/structured-data/article

```
<html>
  <head>
    <title>Article headline</title>
    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "NewsArticle",
      "headline": "Article headline",
      "image": [
        "https://example.com/photos/1x1/photo.jpg",
        "https://example.com/photos/4x3/photo.jpg",
        "https://example.com/photos/16x9/photo.jpg"
       ],
      "datePublished": "2015-02-05T08:00:00+08:00",
      "dateModified": "2015-02-05T09:20:00+08:00",
      "author": [{
          "@type": "Person",
          "name": "Jane Doe",
          "url": "http://example.com/profile/janedoe123"
        },{
          "@type": "Person",
          "name": "John Doe",
          "url": "http://example.com/profile/johndoe123"
      }]
    }
    </script>
  </head>
  <body>
  </body>
</html>
```

**Comment by goforbg** [comment]
Any plan to merge this? Thank you in advance <3

**Comment by LouieRichardson99** [comment]
Is there a reason this PR isn't being merged?

**Comment by xiaotiandada** [comment]
> Apologies, I've been pretty busy. Will be doing a sweep of PR's and issues over the next week.
> 
> @xiaotiandada thank you for the pull request, could you add a Cypress test covering both scenarios? (one with array of strings and one with array of objects)

I copied the `articleOld.tsx` file and added the `renders with all props(old)` test string of array in `article.spec.js`

**Comment by xiaotiandada** [comment]
Supports multiple data formats
```ts
[
  {
    name: 'Jane Blogs',
    url: 'https://example.com',
  },
  {
    name: 'Mary Stone',
    url: 'https://example.com',
  },
  'Jane Blogs',
  undefined,
];

```

**Pull request merged**
