### PR TITLE
make it possible to disable googlebot tags

### PR DESCRIPTION
**Pull request by riccardogiorato**
### dangerouslyDisableGoogleBot
Sometimes it might be possible that googlebot tags need to be removed from the source code of all pages on a website, to fix this usecase I added a single param called:
- dangerouslyDisableGoogleBot, this will be set in the DefaultSeo component disabiling it on all pages

This will fix also this issue where people wanted to add this toggle: https://github.com/garmeeh/next-seo/issues/367

### disableGooglebot

I also added a simple "disableGooglebot" param to NextSeo to be used in all the cases where someone wants to remove googletags but it's not using DefaulySeo and dangerouslyDisableGoogleBot!

--- 

Some things to help get a PR reviewed and merged faster:
- Have you updated the documentation to go with your changes? yes
- Have you written or updated unit tests? yes 
- Have you written an integration test in the test app supplied? yes

As an extra things I also added some E2E test to check for the other dangerously set fields like noindex and nofollow!

### CODE REVIEW

**Comment by riccardogiorato** [comment]
Hello @garmeeh thank you for this great package and I really hope you can take a look at my changes/additions!

Hope to hear from you and thank you for any feedback!

**Review by garmeeh — APPROVED** [review]
Thanks @riccardogiorato! Nice solution 😎

**Comment by garmeeh** [comment]
@all-contributors please add @riccardogiorato code test doc

**Comment by garmeeh** [comment]
Hey @riccardogiorato the CI won't run for some reason on the PR so just ran the tests locally. Looks like the new one is failing. Probably something small if you wouldn't mind taking a look 😅 I will get this released for you then.

**Comment by riccardogiorato** [comment]
Thanks @garmeeh I will look at this tomorrow morning, Central European Time and hopefully before lunch I should be able to fix this!

**Comment by riccardogiorato** [comment]
Hey @garmeeh I just fixed the tests, I moved all the "dangerously" tests to a specific file "cypress/e2e/seo.dangerously.spec.js".

I then also added an extra test to check dangerouslyDisableGooglebot when used in combination with noindex or nofollow.

Adding this test I was able to recognise that I had to move out the code to set the "defaults" for this flag in all cases both when used with noindex or index: https://github.com/garmeeh/next-seo/pull/860/commits/525c6545c09620ddd00755ebcdeaf8118a4d95b4#diff-9ae70e005e068b3df187aa3eb5a641c14efe8977442b115747c9abe33232f04aR160-L168

**Comment by garmeeh** [comment]
Thanks @riccardogiorato. The new tests add much more coverage 💪 Once the build passes I will merge and release.

**Comment by riccardogiorato** [comment]
Hey @garmeeh is the build stuck again? Is it a problem just on this pull request? 
Maybe because my branch name was master too?

**Comment by garmeeh** [comment]
@riccardogiorato strange. Would you mind creating a new pull request from a branch on your repo? I would just like to see if that solves it. I will run the tests locally if not.

**Comment by riccardogiorato** [comment]
Hey @garmeeh can you approve this PR? https://github.com/garmeeh/next-seo/pull/869

I might have found the issue in the other PR if you approve it to be run!

**Pull request closed without merging**
