### PR TITLE
Output esm/cjs/umd files, allow code splitting (closes #4)

### LINKED ISSUE #4: code-splitting
With the latest Next.js canary with webpack 4, it should be possible to publish `.mjs` files where `import` and `export` are not transpiled. This will allow webpack to code-split next-seo.

### PR DESCRIPTION
**Pull request by luke-j**
## Description of Change(s):

Currently only commonJS is output from the build. This prevents tree shaking & code splitting. This PR removes babel and adds [microbundle](https://github.com/developit/microbundle) to output cjs/esm/modern/udm bundles as well as types. 

---

Some things to help get a PR reviewed and merged faster:

- Have you updated the documentation to go with your changes? NA
- Have you written or updated unit tests? NA
- Have you written an integration test in the test app supplied? NA

The above are generally required on all PR's.

Please have a read of the Contributing Guide for full details.

https://github.com/garmeeh/next-seo/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by garmeeh** [comment]
Hey @luke-j thank you for this PR 🙏 

I will review this very shortly.

**Comment by garmeeh** [comment]
Hey @luke-j I finally have some time clearing in my calendar to spend on `next-seo` and hoping to start with this pull request. If you get a chance could you resolve the conflicts and pull in the latest from master? Would love to get this tested and released as soon as that is done.

**Comment by luke-j** [comment]
@garmeeh Conflicts are resolved - this branch should be up to date with master 👍

**Comment by garmeeh** [comment]
@all-contributors please add @luke-j code infra

**Comment by garmeeh** [comment]
Hey @luke-j I have published this under a beta tag `next-seo@4.7.0-beta.0`

I was testing it out on a test app and I getting the following errors:

```
ready - started server on http://localhost:3000
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
/Users/garymeehan/mydev/sandbox/next-seo-test/node_modules/next-seo/lib/next-seo.js:1
import React, { Component } from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at eval (webpack-internal:///next-seo:1:18)
    at Object.next-seo (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:184:1)
    at __webpack_require__ (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:23:31)
    at eval (webpack-internal:///./pages/_app.tsx:7:66)
    at Module../pages/_app.tsx (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:161:1)
    at __webpack_require__ (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:23:31)
    at Object.0 (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:172:18)
    at __webpack_require__ (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:23:31)
    at /Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:91:18
    at Object.<anonymous> (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:94:10)
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
error - /Users/garymeehan/mydev/sandbox/next-seo-test/node_modules/next-seo/lib/next-seo.js:1
import React, { Component } from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at eval (webpack-internal:///next-seo:1:18)
    at Object.next-seo (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:184:1)
    at __webpack_require__ (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:23:31)
    at eval (webpack-internal:///./pages/_app.tsx:7:66)
    at Module../pages/_app.tsx (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:161:1)
    at __webpack_require__ (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:23:31)
    at Object.0 (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:172:18)
    at __webpack_require__ (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:23:31)
    at /Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:91:18
    at Object.<anonymous> (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:94:10)
/Users/garymeehan/mydev/sandbox/next-seo-test/node_modules/next-seo/lib/next-seo.js:1
import React, { Component } from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at eval (webpack-internal:///next-seo:1:18)
    at Object.next-seo (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:184:1)
    at __webpack_require__ (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:23:31)
    at eval (webpack-internal:///./pages/_app.tsx:7:66)
    at Module../pages/_app.tsx (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:161:1)
    at __webpack_require__ (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:23:31)
    at Object.0 (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:172:18)
    at __webpack_require__ (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:23:31)
    at /Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:91:18
    at Object.<anonymous> (/Users/garymeehan/mydev/sandbox/next-seo-test/.next/server/static/development/pages/_app.js:94:10)
```

**Comment by garmeeh** [comment]
I am going to revert master just for now. I have pushed a beta branch that contain all the changes.

**Pull request merged**
