### PR TITLE
[Feature] - OrganizationJsonLD & WebPageJsonLd & BrandJsonLd

### PR DESCRIPTION
**Pull request by adrianu197**
## Description of Change(s):
Adding [Organization](https://schema.org/Organization) schema, there is [a feature request](https://github.com/garmeeh/next-seo/issues/854), also 2 more types, [WebPage](https://schema.org/WebPage) and [Brand](https://schema.org/Brand)
P.S. For organization I allowed the type to be configurable with the default 'Organization', as i needed only the 'Corporation' but maybe other will need other types. 

---

Some things to help get a PR reviewed and merged faster:

- Have you updated the documentation to go with your changes? ✅
- Have you written or updated unit tests? ✅
- Have you written an integration test in the test app supplied? ✅

The above are generally required on all PR's.

Please have a read of the Contributing Guide for full details.

https://github.com/garmeeh/next-seo/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by garmeeh — APPROVED** [review]
Nice work @adrianu197 💪 

I will get this merged and released soon.

**Comment by ScottEAdams** [comment]
Any news on this?

**Comment by adrianu197** [comment]
Hey @garmeeh - is there an issue with this PR? I would really love to use the changes.

**Comment by JamesSingleton** [comment]
It would be nice to have this @garmeeh

**Review by nyedidikeke — APPROVED** [review]

**Pull request merged**
