### PR TITLE
feat(utils/markup): Sanitize markup content with DOMPurify

### PR DESCRIPTION
**Pull request by wyeo**
## Description of Change(s):
DOMPurify sanitizes HTML and prevents XSS attacks
---

Some things to help get a PR reviewed and merged faster:

- Have you updated the documentation to go with your changes?
No
- Have you written or updated unit tests?
No
- Have you written an integration test in the test app supplied?
No

The above are generally required on all PR's.

Please have a read of the Contributing Guide for full details.

https://github.com/garmeeh/next-seo/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by garmeeh** [comment]
Hey @wyeo thanks for the pull request and apologies on the delay in reviewing. 

I only recently realized the oversight in the library on on the fact I do not sanitize. However I think adding this dependency would add a little too much overhead to the library. 

I am thinking there should be a section in the docs outlining next-seo does not sanitize by default and add a couple of examples how you would do so before passing data to next-seo 🤔 

Would love to hear your thoughts on this?

**Comment by wyeo** [comment]
Hello @garmeeh !

Yes, i am agree with you about section in the docs.
For the examples, do you have an alternative to DOMPurify ?

**Comment by garmeeh** [comment]
Hey @wyeo, I don't know of any alternatives off the top of my head. 

I think it would be good to add DOMPurify and then more can be added overtime if needed to give users options.

**Comment by garmeeh** [comment]
@wyeo just going to close this PR for house keeping. Please open a new PR if you would like to update the docs, thanks.

**Pull request closed without merging**
