### PR TITLE
WIP :sparkles: Add og:video:secure_url and og:video:type

### LINKED ISSUE #347: open graph video url, secure_url and video type missing
Need ability to add more details about the open graph video like `og:video:url`  `og:video:secure_url` and `og:video:type`

If this can be added already then great.
If not and you're looking to add these and looking for contributor then i'm in.

### PR DESCRIPTION
**Pull request by TomPradat**
## Description of Change(s):

Fix #347 

---

Some things to help get a PR reviewed and merged faster:

- Have you updated the documentation to go with your changes?

Not yet

- Have you written or updated unit tests?

I couldn't find tests about `og:video`. Should i write some ? Maybe in another PR ?

- Have you written an integration test in the test app supplied?

Same than above

### CODE REVIEW

**Review by garmeeh — COMMENTED** [review]
Thanks for the PR @TomPradat. It's looking good. If you want to just add these new properties to docs that would be great.

If you could also add a check in `seo.spec.js` in the test below:

```
it('SEO overrides apply correctly', () => {
```

You should see some examples in there, let me know if its not clear and I can lend a hand.

**Comment by kahoowkh** [comment]
@TomPradat I see this PR hasn't been updated for 2 months. I can help you in updating the tests and documentation.

**Comment by TomPradat** [comment]
Yeap sorry, I had a busy end of year and then honestly forgot about it. I'll work on this 👍

**Comment by garmeeh** [comment]
@all-contributors please add @TomPradat code

**Pull request merged**
