### PR TITLE
feat(minify-json-ld): minifies jsonLd output

### PR DESCRIPTION
**Pull request by igormartimiano**
## Description of Change(s):

Minifies the jsonLd content before rendering it on `<Head>`
I'm not entirely sure if this is the most efficient way of doing this, but definitely reliable and doesn't add any extra deps. I'd rather have the extra computational work than no compression at all. 

Closes https://github.com/garmeeh/next-seo/issues/263#issue-592275986

---

Some things to help get a PR reviewed and merged faster:

- Have you updated the documentation to go with your changes?
Not sure if it should be mentioned anywhere in the docs, up to suggestions. Would be no problem to do it
- Have you written or updated unit tests?
Didn't find any jsonLd related unit tests, and I didn't write any
- Have you written an integration test in the test app supplied?
Didn't write it but I tested on the test app and also ran cypress locally

### CODE REVIEW

**Comment by garmeeh** [comment]
@igormartimiano very nice solution 👏 

🤔 I just did a quick search and on larger data sets it may cause an issue but for this library I can't imagine that being an issue. 

I wonder should we add a flag that to opt out? Just thinking if any site has an issue with it they can quickly opt out.

Although this may be overkill...

**Comment by igormartimiano** [comment]
@garmeeh Thanks, glad to help!
Could you provide resources about this particular issue? Wasn't aware of that. If it's critical enough, I think we should try to minify doing something else instead of adding a flag to opt out of the feature. I see that kind of flag as a workaround to a bug that shouldn't be there in the first place and wouldn't go that route unless it is absolutely necessary to provide the feature with a certain implementation. 
When I have enough time I'll also give it a search. I really would have to get a better grasp of the issue to discuss.
But, ultimately, from my experience schemas aren't very large data sets anyway.

**Comment by garmeeh** [comment]
@igormartimiano yeah I totally agree, I think I might be just a little too cautious. As I said, I only gave it a quick search so really shouldn't base any assumptions on a that 😅 

I think as it stands it is a nice addition and does not add any overhead. If an issue arises it can be addressed then. 

I'm happy to merge and release this if you are?

**Comment by igormartimiano** [comment]
@garmeeh Alright then, looks good to me 👌🏻

**Review by garmeeh — APPROVED** [review]

**Pull request merged**
