### PR TITLE
Add Next.js 10 peer dependency

### PR DESCRIPTION
**Pull request by danielr18**
## Description of Change(s):
The tests with Next.js 10 passed in this PR https://github.com/garmeeh/next-seo/pull/554.

### CODE REVIEW

**Comment by garmeeh** [comment]
@all-contributors please add @danielr18 code

**Review by garmeeh — APPROVED** [review]
Thank you

**Comment by danielr18** [comment]
Thanks @garmeeh for the quick response. If you don't mind, would you be able to change the `hacktoberfest-accepted` topic in the repo to `hacktoberfest`? `hacktoberfest-accepted` is for PR labels.

**Comment by garmeeh** [comment]
@danielr18 done.

**Pull request merged**
