### PR TITLE
[Feature] softwareApp  jsonld

### PR DESCRIPTION
**Pull request by shaswatsaxena**
## Description of Change(s):
---
Added support for Software Application This PR adds #617. 

Some things to help get a PR reviewed and merged faster:

- Have you updated the documentation to go with your changes? Yes
- Have you written or updated unit tests? No
- Have you written an integration test in the test app supplied? Yes

The above are generally required on all PR's.

Please have a read of the Contributing Guide for full details.

https://github.com/garmeeh/next-seo/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by garmeeh** [comment]
Hey @shaswatsaxena thanks for the contribution. I have not reviewed it just yet. 

To be fair, I would like to check with @CedYF has he started working on this feature as he stated in #617 that he intended on working on it.

**Comment by garmeeh** [comment]
Hey @shaswatsaxena thanks for the patience and understanding on this change request. I did not hear anything back so would be more than happy to proceed with yours.

Would you be able to resolve the conflict and I will review this then.

**Comment by shaswatsaxena** [comment]
Hi @garmeeh, I have resolved the conflicts.

**Comment by garmeeh** [comment]
@all-contributors please add @shaswatsaxena code doc test

**Review by garmeeh — APPROVED** [review]
Thanks for the contribution 😄

**Pull request merged**
